name: Linting

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main


jobs:
  flake8-lint-doc:
    runs-on: ubuntu-latest
    name: Doc Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: python -m pip install pydoclint[flake8]
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          args: "--select=DOC --style=sphinx"
  flake8-lint:
    runs-on: ubuntu-latest
    name: Flake8 Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
  black:
    runs-on: ubuntu-latest
    name: Black Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - uses: psf/black@stable